export const BASE_URL_LOCAL="http://localhost:8080"
export const BASE_URL_LOCAL2="https://quaint-adele-alevivaldi-a5632bd1.koyeb.app"

export const TOKEN_KEY = "br.com.alexcosta/token"
export const DADOS_USER = "br.com.alexcosta/user"
export const storageCarrinho = "br.com.alexcosta/carrinho"

export const CLIENTE_ID = "myclientid"
export const CLIENTE_SECRET="myclientsecret"
export const LOGIN = "/api/login/cliente3"
export const RECUPERAR_SENHA = "/api/recuperacao/solicitar"
export const ALTERAR_SENHA_AUTENTICADO = "/api/recuperacao/alterar"
export const CADASTRO_NOVO_USUARIO = "/api/usuarios/cadastro"
export const TEXTO_PADRAO_SOLICITACAO="Aguarde, estamos processando sua solicitação..."
export const ENVIAR_PEDIDO = "/api/pedidos/salvar"
export const HISTORICO_PEDIDO_USER="/api/pedidos/usuario"
export const PAGAMENTO = "/api/payments"
export const PUBLIC_STRIPE = "pk_test_51KQ4TFI8FQmw3JIIKhoW9sTJCrnDyx8z2rVjPD6tS2nbs59EpcQ8e2GtudrxTl6okXC5CYGvkfWhefrangs1kPMg00nE5QItPC"
export const PRIVATE_STRIPE = "sk_test_51KQ4TFI8FQmw3JIIlZTawdkOW6IR5qWJEO6HwCTwmcb0Msj2fGcpGeUNcmPt9Lw3XLARQPY6Ux6Mo7M8QbFQZsmF00pFQ7birw"